### PR TITLE
Enable non vx works iocs

### PR DESCRIPTION
**Pull request by dirk-zimoch**
This change allows to build the driver on non vxWorks systems (e.g. embedded Linux with VME bus support).
Several dubious casts fixed and some code cleanup.

### CODE REVIEW

**Comment by MarkRivers** [comment]
When making a number of substantive changes it is helpful to not also make a large number of cosmetic white space changes.  It makes it hard for reviewers to focus on the important changes.

**Comment by dirk-zimoch** [comment]
That's why I did it in a separate commit. But I can take it out if you want.

**Comment by anjohnson** [comment]
@dirk-zimoch Many (most?) reviewers will be looking at the Files Changed tab of the PR on the GitHub website, not at your individual commits. Collecting the white-space changes into a separate commit is a good thing, but it doesn't change what the tab shows the reviewers. If you have white-space cleanups that you want merging I would include a note in the PR to say they are coming but only push them to the branch once the reviewers are happy with the code changes but before the final merge (or put them in a separate PR).

**Comment by anjohnson** [comment]
For the record while I haven't tested them at all, I agree with and approve of all the changes that Dirk is proposing here.

**Comment by dirk-zimoch** [comment]
I will re-push without the whitespace cleanup...

**Comment by dirk-zimoch** [comment]
Better?

**Pull request merged**
